import logging
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import markdown as md
from jinja2 import Environment, FileSystemLoader

from .models import Summary

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

# Display order for themes
THEME_ORDER = ["Tech", "Finance", "Health", "General"]


def send_digest_email(
    summaries: list[Summary],
    sender: str,
    recipient: str,
    app_password: str,
    subject_prefix: str = "Podcast Digest",
) -> bool:
    """Compose and send the daily digest email via Gmail SMTP."""
    if not summaries:
        logger.info("No summaries to send — skipping email.")
        return False

    date_str = datetime.now(timezone.utc).strftime("%A, %B %d, %Y")
    subject = f"{subject_prefix} — {date_str}"

    # Group summaries by theme
    themes, theme_order = _group_by_theme(summaries)

    # Render HTML
    html_content = _render_html(summaries, themes, theme_order, subject_prefix, date_str)

    # Build plain text fallback
    plain_content = _render_plain_text(summaries, themes, theme_order, subject_prefix, date_str)

    # Compose email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient

    msg.attach(MIMEText(plain_content, "plain"))
    msg.attach(MIMEText(html_content, "html"))

    # Send via Gmail SMTP
    try:
        logger.info(f"Sending digest email to {recipient}...")
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(sender, app_password)
            server.send_message(msg)
        logger.info("Email sent successfully!")
        return True
    except smtplib.SMTPException as e:
        logger.error(f"Failed to send email: {e}")
        return False


def _group_by_theme(summaries: list[Summary]) -> tuple[dict[str, list[Summary]], list[str]]:
    """Group summaries by theme, maintaining display order."""
    themes: dict[str, list[Summary]] = {}
    for s in summaries:
        theme = s.episode.theme
        if theme not in themes:
            themes[theme] = []
        themes[theme].append(s)

    # Order themes according to THEME_ORDER, then any extras alphabetically
    ordered = [t for t in THEME_ORDER if t in themes]
    extras = sorted(t for t in themes if t not in THEME_ORDER)
    theme_order = ordered + extras

    return themes, theme_order


def _render_html(
    summaries: list[Summary],
    themes: dict[str, list[Summary]],
    theme_order: list[str],
    subject_prefix: str,
    date: str,
) -> str:
    """Render the HTML email template."""
    env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))
    env.filters["markdown"] = lambda text: md.markdown(text, extensions=["nl2br"])
    episode_ids = {s.episode.guid: i for i, s in enumerate(summaries)}
    template = env.get_template("email_template.html")
    return template.render(
        summaries=summaries,
        themes=themes,
        theme_order=theme_order,
        subject_prefix=subject_prefix,
        date=date,
        episode_count=len(summaries),
        episode_ids=episode_ids,
    )


def _render_plain_text(
    summaries: list[Summary],
    themes: dict[str, list[Summary]],
    theme_order: list[str],
    subject_prefix: str,
    date: str,
) -> str:
    """Render a plain text version of the digest."""
    lines = [
        f"{subject_prefix}",
        f"{date}",
        f"{len(summaries)} episode{'s' if len(summaries) != 1 else ''} summarized",
        "",
        "=" * 60,
        "",
    ]

    for theme in theme_order:
        lines.append(f"{'─' * 20} {theme} {'─' * 20}")
        lines.append("")
        for summary in themes[theme]:
            lines.append(f"  {summary.episode.podcast_name}")
            lines.append(f"  {summary.episode.title}")
            lines.append(f"  Source: {summary.transcript_source}")
            lines.append("")
            lines.append(summary.content)
            lines.append("")
            lines.append("-" * 60)
            lines.append("")

    lines.append("Generated by Podcast Digest Agent")
    return "\n".join(lines)
